shell-fmt autoformatter now in use

diff --git a/jupyterlab-workspaces b/jupyterlab-workspaces
--- a/jupyterlab-workspaces
+++ b/jupyterlab-workspaces
@@ -5,12 +5,14 @@
 # takes as stdin all json files in the jupyter config path,
 # under the directories /lab/workspaces, and uses jq to fetch the names
 
-
 # for references for command, see here:
 # https://stackoverflow.com/a/677212/12445701
 
-command -v jq >/dev/null 2>&1 || { echo >&2 "jq is required but it's not installed. Aborting."; exit 1; }
+command -v jq >/dev/null 2>&1 || {
+    echo >&2 "jq is required but it's not installed. Aborting."
+    exit 1
+}
 
-for _WORKSPACE in "$JUPYTER_CONFIG_DIR"/lab/workspaces/* ; do 
+for _WORKSPACE in "$JUPYTER_CONFIG_DIR"/lab/workspaces/*; do
     jq -r ".metadata.id" "$_WORKSPACE"
 done
